server:
  port: 8080
spring:
  application:
    name: spring-ai
    datasource:
      url: jdbc:postgresql://localhost:5432/spring-ai
      username: postgres
      password: password
      driver-class-name: org.postgresql.Driver
    jpa:
      properities:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
  ai:
    openai:
      api-key: AIzaSyDZraR82PYB0pfBlE5z46e9IRrhryCqxGE
      chat:
        base-url: https://generativelanguage.googleapis.com
        completions-path: /v1beta/openai/chat/completions
        options:
          model: gemini-2.0-flash
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
